DEBUG: false
HASS_BASE_TOPIC: homeassistant
HASS_BIRTH_GRACETIME: 15
HASS_ENABLE: false
MODBUS_FRAMER: rtu
MODBUS_IP: espressif
MODBUS_PORT: 5743
MODBUS_RETRIES: 3
MODBUS_SLAVE: 252
MODBUS_TIMEOUT: 5
MQTT_DISABLE: false
MQTT_FLOAT_FORMAT: '{:.3f}'
MQTT_LOGIN: ' '
MQTT_PASSWORD: ''
MQTT_PORT: 1883
MQTT_SERVER: localhost
MQTT_TOPIC: MTEC
REFRESH_CONFIG: 3605
REFRESH_DAY: 300
REFRESH_NOW: 10
REFRESH_TOTAL: 310
